### post Product
POST http://127.0.0.1:8000/products/

{"pname": "เดรส Zara สีแดง",
  "price": 790,
  "brand": "Zara",
  "description": "ใส่ครั้งเดียว สภาพใหม่มาก",
  "categoryID": 4,
  "seller_id": 2,
  "tags": "เดรส, zara, เสื้อผ้า",
  "product_status": "available",
  "image_url": "https://th.bing.com/th/id/OIP.nBtQXbc56tKup3D1zq4GcgHaHa?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3"
}

###get product by id
GET http://127.0.0.1:8000/products/21

###get all products
GET http://127.0.0.1:8000/products/

###อัพเดต product
PUT http://127.0.0.1:8000/products/18

{
  "pname": "กระเป๋า Coach มือสอง",
  "price": null,
  "brand": "",
  "description": "",
  "categoryID": 0,
  "seller_id": 0,
  "tags": "",
  "product_status": ""
}

###Create order
POST http://127.0.0.1:8000/create-order/

{
  "cus_id": 4,
  "items": [
    {
      "product_id": 13,
      "qty": 1
    },
    {
      "product_id": 2,
      "qty": 1
    },
    {
      "product_id": 10,
      "qty": 1
    }
  ],
  "shipping_cost": 45
}

### Get all order 
GET http://127.0.0.1:8000/orders

### Get order by ID
GET http://127.0.0.1:8000/orders/16

###get order + item
GET http://127.0.0.1:8000/order_items/16

### Cancel Order
PUT http://127.0.0.1:8000/orders/16/cancel

###เปลี่ยนสถานะ order (confirmed, shipping, delivery)
PATCH http://127.0.0.1:8000/orders/16/status?status=cancelled


###Payments
POST http://127.0.0.1:8000/payments/

{
  "order_id": 7,
  "payment_method": "qr_code",
  "payment_amount": 2640.00,
  "payment_status": "success",
  "payment_date": "2026-02-16T11:30:00",
  "transaction_no": "TXN20014568"
}

### Get all payments
GET http://127.0.0.1:8000/payments/

### Get payment by id
GET http://127.0.0.1:8000/payments/4


###Customer 
POST http://127.0.0.1:8000/customers/

{
  "username": "namfon_shop",
  "email": "namfon.k@gmail.com",
  "customer_phone": "0878888888"
}

###Customer เพิ่มเติม
POST http://127.0.0.1:8000/customers/

[
  {
    "username": "madam_jue",
    "email": "jue@gmail.com",
    "customer_phone": "0912345678",
    "password": "password123",
    "display_name": "มาดามจือ",
    "avatar": "https://hauterrfly.com/wp-content/uploads/2025/10/aespa-giselle-tattoo-backlash-misogynistic-backlash.jpg"
  },
  {
    "username": "kikidoyouloveme",
    "email": "leena@gmail.com",
    "customer_phone": "0987654321",
    "password": "password123",
    "display_name": "ลีน่าจัง",
    "avatar": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOxqzW9JSe7pOmbjCUXdlPxBzEvkhKBUrI5g&s"
  },
  {
    "username": "veggie_girl",
    "email": "veggie@gmail.com",
    "customer_phone": "0922222222",
    "password": "password123",
    "display_name": "น้องผัก",
    "avatar": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyszNIwM59Yja6anjgdZoSeP6XACdto22acQ&s"
  },
  {
    "username": "yippeee",
    "email": "yippee@gmail.com",
    "customer_phone": "0933333333",
    "password": "password123",
    "display_name": "เย้ๆๆๆ",
    "avatar": "https://i.pinimg.com/1200x/bb/10/5a/bb105a7c0fa94cfce7a2ec8fc4dc5d55.jpg"
  },
  {
    "username": "imnaim_",
    "email": "rosie@gmail.com",
    "customer_phone": "0944444444",
    "password": "password123",
    "display_name": "rosie",
    "avatar": "https://i.pinimg.com/736x/08/01/e2/0801e233c0533e1fbfbab744b9155d57.jpg"
  }
]

###Get all customers
GET http://127.0.0.1:8000/customers/

###Get customer by id
GET http://127.0.0.1:8000/customers/10

###Seller
POST http://127.0.0.1:8000/sellers/

{
  "seller_name": "Namfon Kanyarat",
  "email": "namfon.boutique@gmail.com",
  "seller_phone": "0855678901",
  "store_name": "Namfon Boutique",
  "verification_status": "verified"
}

###Get all sellers
GET http://127.0.0.1:8000/sellers/

###Get seller by id
GET http://127.0.0.1:8000/sellers/2

###Search product
#ค้นหาทั่วไป + Sort ราคาต่ำ - สูง
POST http://127.0.0.1:8000/products/search

{
  "query": "เสื้อ",
  "sort_by": "price_low",
  "page": 1,
  "page_size": 20
}

### Filter by Brand
POST http://127.0.0.1:8000/products/search

{
  "brand": "Uniqlo",
  "page": 1
}

###Filter by Category
POST http://127.0.0.1:8000/products/search

{
  "category_id": 1,
  "sort_by": "price_high",
  "page": 1
}

###Filter by Tags
POST http://127.0.0.1:8000/products/search

{
  "tags": ["หมวก"],
  "sort_by": "newest",
  "page": 1
}